name: Bedwars
version: ${project.version}
main: net.craftions.bedwars.Bedwars
api-version: 1.16
commands:
  setspawner:
    permission: bedwars.command.setspawner
    usage: /setspawner <type>
  setspawn:
    permission: bedwars.command.setspawn
    usage: /setspawn
  spawn:
    permission: bedwars.command.spawn
    usage: /spawn
  start:
    permission: bedwars.command.start
    usage: /start